name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always
      TOOLCHAIN_VERSION: nightly-2024-12-09

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.TOOLCHAIN_VERSION }}
          override: true

      # if build fails, we don't publish
      - name: Build
        run: cargo build --release

      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
